# Introduction

In [4]:
2+3

5

In [5]:
9-8

1

In [6]:
4*6

24

In [9]:
8/4 #when we divide numbers there is a chance of getting decimal values so we get float as answer

2.0

In [10]:
5/2

2.5

In [11]:
5//2 #integer output - floor division or integer division

2

In [12]:
8 + 9 - 10

7

In [13]:
8 + 2*3 #PEMDAS

14

In [14]:
(8+2)*3

30

In [15]:
2**3 # POWER OF

8

In [16]:
10 % 3 # MOdulus operator and remainder as output

1

In [17]:
'navin'

'navin'

In [18]:
print('navin')

navin


In [21]:
#print('navin's laptop')
print("navin's laptop")

navin's laptop


In [22]:
print('navin "laptop"')

navin "laptop"


In [23]:
print('navin\'s "laptop"')

navin's "laptop"


In [24]:
'navin'+'navin'

'navinnavin'

In [25]:
10*'sai'

'saisaisaisaisaisaisaisaisaisai'

In [26]:
print('c:\docs\navin')

c:\docs
avin


In [27]:
print('c:\docs\\navin')

c:\docs\navin


In [28]:
print(r'c:\docs\navin')

c:\docs\navin


# Variables

In [30]:
x = 2
x

2

In [31]:
x + 3

5

In [32]:
y = 3
x + y

5

In [34]:
x = 9
x

9

In [35]:
x + y

12

In [36]:
x

9

In [59]:
#abc
#undefined variable

In [38]:
x + 10

19

In [41]:
_ + y #underscore represents the value of output obtained from the previous operation

25

In [43]:
name = 'youtube'
name

'youtube'

In [44]:
name + 'rocks'

'youtuberocks'

In [45]:
#name ' rocks'
#this will throw an error

In [47]:
name[0] # first word

'y'

In [48]:
name[6] # last word

'e'

In [50]:
#name[8]
#throws an error as the limit is being crossed

In [52]:
name[-1] #goes in a reverse order

'e'

In [53]:
name[0:2]

'yo'

In [55]:
name[1:4] #starts with index 1 and ends before the index 4

'out'

In [56]:
name[1:]

'outube'

In [57]:
name[:]

'youtube'

In [58]:
name[:4]

'yout'

In [60]:
name[3:10]

'tube'

In [62]:
#name[0:3] = "my"
#string object doesnot support item assignment or immutable

In [63]:
'my '+ name[3:]

'my tube'

In [65]:
myname = "Sai"
len(myname)

3

# List

In [67]:
nums = [25, 12,36, 95, 14]

In [68]:
nums

[25, 12, 36, 95, 14]

In [69]:
nums[0]

25

In [70]:
nums[4]

14

In [71]:
nums[2:]

[36, 95, 14]

In [72]:
nums[-1]

14

In [73]:
nums[-5]

25

In [74]:
names = ['sai','rohit']

In [75]:
names

['sai', 'rohit']

In [78]:
values = [9.5,'sai',25] #stores different type of values in a single variable

In [77]:
values

[9.5, 'sai', 25]

In [79]:
mil = [nums, names]

In [80]:
mil

[[25, 12, 36, 95, 14], ['sai', 'rohit']]

In [81]:
nums.append(45)  #list is mutable

In [82]:
nums

[25, 12, 36, 95, 14, 45]

In [83]:
nums.clear

<function list.clear>

In [84]:
nums.insert(1,77)

In [85]:
nums

[25, 77, 12, 36, 95, 14, 45]

In [89]:
nums.remove(95)
nums

[25, 77, 12, 36, 45]

In [91]:
nums.pop(1)
nums

[25, 36, 45]

In [93]:
nums.pop() # last element which is added gets removed
nums

[25]

In [94]:
del nums[1:]

In [95]:
nums

[25]

In [97]:
nums.extend([29,12,14,36])
nums

[25, 29, 12, 14, 36, 29, 12, 14, 36]

In [98]:
min(nums)

12

In [99]:
max(nums)

36

In [100]:
sum(nums)

207

In [102]:
nums.sort()
nums

[12, 12, 14, 14, 25, 29, 29, 36, 36]

# Tuple


In [104]:
tup = (21,36,14,25)
tup

(21, 36, 14, 25)

In [106]:
tup.count

<function tuple.count>

# Set

In [108]:
s = {21,25,14,5}
s

{5, 14, 21, 25}

In [110]:
s = {25,14,98,63,75,98,99}
s


{14, 25, 63, 75, 98, 99}

# Sample

In [111]:
num = 5

In [112]:
id(num)

94278650329760

In [113]:
name = 'sai'

In [114]:
id(name)

139964883218760

In [115]:
a = 10
b = a

In [116]:
id(a) #both the variables point to the same address box
id(b)

94278650329920

In [117]:
id(10)

94278650329920

In [118]:
k = 10
id(k)

94278650329920

In [119]:
a = 9
id(a)

94278650329888

In [120]:
id(b)

94278650329920

In [121]:
#in python constant doesn't exist
type(a)

int

# Data types

In [122]:
num = 2.5
type(num)

float

In [123]:
num = 5
type(num)

int

In [124]:
num = 6 + 9j
type(num)

complex

In [126]:
a = 5.6
b = int(a)
b
type(b)

int

In [129]:
k = float(b)
k

5.0

In [131]:
k = 6
c = complex(b,k)
c

(5+6j)

In [132]:
b<k

True

In [134]:
bool = b < k
bool

True

In [135]:
int(True)

1

In [136]:
int(False)

0

In [137]:
lst = [25,35,45,12]
type(lst)

list

In [139]:
s = {25,36,45,15,12,25}
s

{12, 15, 25, 36, 45}

In [140]:
type(s)

set

In [141]:
t = (25,36,4,57,12)
type(t)

tuple

In [142]:
str = "sai"
st = 'a'
type(st)

str

In [143]:
range(10)

range(0, 10)

In [144]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [145]:
list(range(2,10,2))

[2, 4, 6, 8]

In [146]:
type(range(10))

range

In [148]:
d = {'sai':'sms','rohit':'iphone'}
d

{'rohit': 'iphone', 'sai': 'sms'}

In [149]:
d.keys()

dict_keys(['sai', 'rohit'])

In [150]:
d.values()

dict_values(['sms', 'iphone'])

In [156]:
d['sai']

'sms'

In [157]:
d.get('kiran')

# Operators

In [1]:
x = 2
y = 3
x + y
x - y
x * y
x/y
x = 8

In [2]:
x + y

11

In [3]:
x - y

5

In [4]:
x * y

24

In [5]:
x / y

2.6666666666666665

In [164]:
x = x + 2
x

12

In [166]:
x +=2
x

16

In [168]:
x*=3
x

144

In [6]:
a,b = 5,6
a
b


6

In [172]:
n = 7 #Unary Operator
n = -n
n

-7

In [173]:
a < b

True

In [174]:
a ==b

False

In [175]:
a <=b

True

In [176]:
a!=b

True

In [177]:
a = 5
b = 4
a < 8 and b < 5

True

In [178]:
a < 8 and b < 2

False

In [179]:
a < 8 or b < 2

True

In [180]:
x = True
x

True

In [181]:
not x

False

In [182]:
x

True

In [8]:
bin(25)   #converting 25 to binary system

'0b11001'

In [9]:
0b0101 #binary to decimal system

5

In [10]:
oct(25)   #converting 25 to octal system

'0o31'

In [11]:
hex(25) #converting 25 to Hexa decimal system

'0x19'

In [12]:
hex(10)

'0xa'

In [13]:
0xf

15

# How to swap two numbers in python

In [14]:
a = 5
b = 6
temp = a
a = b
b = temp
print(a)
print(b)
# in this example we are wasting one extra variable

6
5


In [15]:
a = 5
b = 6
a = a + b
b = a - b
a = a - b
print(a)
print(b)
# in this example we are wasting one extra bit for storing value of a = 11

6
5


In [18]:
a = 5
b = 6

a = a ^ b
b = a ^ b
a = a ^ b
print (a)
print (b)
# this is XOR

6
5


In [20]:
a = 5
b = 6

a,b = b,a
print(a)
print(b)
# it works on the basis of Rot_two in a stack behind the scene

6
5


# Bitwise Operators

In [22]:
~12  #gives the binary complement of this number

-13

In [23]:
bin(12)

'0b1100'

In [24]:
12 & 13   # Applies and to all the bits of both the numbers

12

In [25]:
12|13   #Applies or to all the bits of both the numbers

13

In [26]:
25 & 30

24

In [28]:
12 ^ 13 # applies xor to all the bits of both the numbers


1

In [30]:
10 << 2  # the dot to represent the decimal system is shifted towards leftside by two bits

40

In [32]:
10 >> 2

2

# Math functions

In [33]:
import math #import math module
x = math.sqrt(25)
x

5.0

In [38]:
x = math.sqrt(15)
x

3.872983346207417

In [39]:
print(math.floor(x))

3


In [40]:
print(math.ceil(x))

4


In [41]:
print(math.pow(3,2))

9.0


In [42]:
print(math.pi)

3.141592653589793


In [43]:
print(math.e)

2.718281828459045


In [44]:
import math as m # alias
print(m.sqrt(25))

5.0


In [46]:
from math import sqrt,pow
pow(4,5)

1024.0

In [47]:
help(math) #gives complete information of anything in python

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.6/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
 

# Input Function

In [50]:
x = input("Enter x")
y = input("Enter y") #input function always deals with string type so whatever the input is given is concatenated
z = int(x) + int(y)  # typecasting converting string to integer
print(z)

Enter x5
Enter y2
7


In [51]:
ch  = input('enter a char')
print (ch[0])

enter a charpqr
p


In [52]:
ch  = input('enter a char')[0]
print (ch)

enter a charpqr
p


In [53]:
result = eval(input('enter an expression'))

print(result)

enter an expression5+6
11


In [56]:
import sys
x = int(sys.argv[1])
y = int(sys.argv[2])
z = x + y
print(z)
#for giving value in the command line when you call the python file name


ValueError: invalid literal for int() with base 10: '-f'

# Conditional Statements

In [1]:
if False:
    print("In right")
    print("542")
print("Bye")

Bye


In [6]:
x = 4
if x%2==0:
    print ("Even")
    if x>5:              #Nested if else
        print("Great")
    else:
        print("Not great")
else:
    print ("Odd")

Even
Not great


In [7]:
x = 2
if x==1:
    print("One")
elif x==2:
    print("Two")
else:
    print("Other")

Two


# Looping

In [9]:
i = 1 # initialization
while i<=5: #condition
    print("t")   #execution
    i = i + 1   #iteration

t
t
t
t
t


In [10]:
i = 1 # initialization
while i<=5: #condition
    print("t",i)   #execution
    i = i + 1   #iteration

t 1
t 2
t 3
t 4
t 5


In [11]:
i = 1 
j = 1
while i<=5:
    print("t")   
    while j<=4:
        print("r")
        j=j+1
    i = i + 1  

t
r
r
r
r
t
t
t
t


In [14]:
i = 1 

while i<=5:
    print("t",end="")   
    j = 1
    while j<=4:
        print("r",end="")
        j=j+1
    print()    
    i = i + 1  

trrrr
trrrr
trrrr
trrrr
trrrr


In [1]:
x = 'NAVIN'
for i in x:
    print(i)

N
A
V
I
N


In [3]:
for i in [2,6,'paul']:
    print (i)

2
6
paul


In [4]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
for i in range(11,21,1):
    print(i)

11
12
13
14
15
16
17
18
19
20


In [6]:
for i in range(20,11,-1):
    print(i)

20
19
18
17
16
15
14
13
12


In [7]:
for i in range(1,21):
    if(i%5!=0):
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19


In [4]:
available = 10
x = int(input("How many candies do you want?"))
i = 1
while i <=x:
    if x>available:
        break
    print("Candy")
    i+=1
print("Bye")

How many candies do you want?15
Bye


In [6]:
for i in range(1,101):
    if i%3==0 or i%5==0:
        continue
    print(i)
print("Bye")

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
52
53
56
58
59
61
62
64
67
68
71
73
74
76
77
79
82
83
86
88
89
91
92
94
97
98
Bye


In [8]:
for i in range(1,101):
    if i%2!=0:
        pass
    else:
      print(i)
print("Bye")

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
Bye


# Patterns 

In [10]:
print("# ",end="")
print("# ",end="")

# # 

In [13]:
for j in range(4):
    for i in range(4):
        print("# ",end="") 
    print()    

# # # # 
# # # # 
# # # # 
# # # # 


In [16]:
for j in range(4):
    for i in range(j+1):
        print("# ",end="") 
    print() 

# 
# # 
# # # 
# # # # 


In [17]:
for j in range(4):
    for i in range(4-j):
        print("# ",end="") 
    print() 

# # # # 
# # # 
# # 
# 


# For Else

In [20]:
nums = [12,15,10,21,26]
for num in nums:
    if num%5==0:
        print(num)
        break
    else:
        print("not found")

not found
15


In [21]:
nums = [12,15,10,21,26]
for num in nums:
    if num%5==0:
        print(num)
        break
else:
        print("not found")

15


# Prime or Not

In [24]:
num = 7
for i in range(2,num):
    if num%i==0:
        print("Not Prime")
        break
else:
    print("Prime")

Prime


# Array

In [25]:
from array import *
vals = array('i',[5,9,4,2])
print(vals)

array('i', [5, 9, 4, 2])


In [26]:
print(vals.buffer_info())

(140440659517904, 4)


In [27]:
print(vals.typecode)

i


In [30]:
vals.reverse()
print(vals)

array('i', [5, 9, 4, 2])


In [32]:
for i in range(4):
    print(vals[i])

5
9
4
2


In [33]:
for val in vals:
    print(val)

5
9
4
2


In [36]:
newarr = array(vals.typecode,(a for a in vals))
print (newarr)

array('i', [5, 9, 4, 2])


In [37]:
newarr = array(vals.typecode,(a*a for a in vals))
print (newarr)

array('i', [25, 81, 16, 4])


In [1]:
from array import *
arr = array('i',[])
n = int(input("Enter the length of the array"))
for i in range(n):
    x = int(input("Enter the next value"))
    arr.append(x)
print(arr)

Enter the length of the array5
Enter the next value1
Enter the next value2
Enter the next value3
Enter the next value4
Enter the next value5
array('i', [1, 2, 3, 4, 5])


In [3]:
val = int(input("Enter the value for search"))
k = 0
for e in arr:
    if e==val:
        print(k)
        break
    k+=1    
print(arr.index(val))

Enter the value for search5
4
4


# Numpy

In [7]:
from numpy import *
arr = array([1,2,3,4,5],int)
arr1 = array([1,2,3,4,5])
print(arr)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5]


In [15]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
print(arr.dtype)

arr1 = array([1,2,3.5])  #all the values are converted to float
print(arr1) #implicit conversion of data types by python itself
print(arr1.dtype)

arr2 = array([1,2,3,4,5],float)
print(arr2)
print(arr2.dtype)

[1 2 3 4 5]
int64
[1.  2.  3.5]
float64
[1. 2. 3. 4. 5.]
float64


In [18]:
arr = linspace(0,16,10) #start,end, number of parts need to broken into. By default number parts is 50.
print(arr)

[ 0.          1.77777778  3.55555556  5.33333333  7.11111111  8.88888889
 10.66666667 12.44444444 14.22222222 16.        ]


In [20]:
arr = arange(1,15,2)#start, end, steps
print(arr)

[ 1  3  5  7  9 11 13]


In [23]:
arr = logspace(1,40,5)
print(arr)
print('%2f' %arr[0])

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
10.000000


In [25]:
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [26]:
arr= ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [27]:
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [37]:
from numpy import *
arr = array([1,2,3,4,5])
arr = arr + 5
print (arr)
arr1 = array([2,4,6,5,2])
arr3 = arr1 + arr  #This operation is called Vectorized Operation
print(arr3)
print(sin(arr1))
print(cos(arr1))
print(log(arr1))
print(sqrt(arr1))
print(max(arr1))
print(min(arr1))
print(concatenate([arr,arr1]))

[ 6  7  8  9 10]
[ 8 11 14 14 12]
[ 0.90929743 -0.7568025  -0.2794155  -0.95892427  0.90929743]
[-0.41614684 -0.65364362  0.96017029  0.28366219 -0.41614684]
[0.69314718 1.38629436 1.79175947 1.60943791 0.69314718]
[1.41421356 2.         2.44948974 2.23606798 1.41421356]
6
2
[ 6  7  8  9 10  2  4  6  5  2]


In [42]:
#How to copy an array
from numpy import *
arr1 = array([1,2,3,4,5])
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
#This is called Aliasing. Both the arrays are pointing to the same address which contains same array value.

[1 2 3 4 5]
[1 2 3 4 5]
140137737071472
140137737071472


In [44]:
from numpy import *
arr1 = array([1,2,3,4,5])
arr2 = arr1.view() #this gives different values with different address
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2)) 

[1 2 3 4 5]
[1 2 3 4 5]
140137736779696
140137736781616


In [45]:
#Shallow Copying: Both the arrays are dependent on each other
from numpy import *
arr1 = array([1,2,3,4,5])
arr2 = arr1.view()
arr1[1]=7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 7 3 4 5]
[1 7 3 4 5]
140137736780896
140137736781376


In [48]:
#Deep Copying : Both the arrays are independent of each other
from numpy import *
arr1 = array([1,2,3,4,5])
arr2 = arr1.copy()
arr1[1]=7
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[1 7 3 4 5]
[1 2 3 4 5]
140137736777856
140137737071472


In [58]:
from numpy import *
arr1 = array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
print (arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
arr2 = arr1.flatten()
print(arr2)
arr3 = arr2.reshape(3,4)
print(arr3)
arr4 = arr2.reshape(2,2,3)
print(arr4)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
2
(2, 6)
12
[1 2 3 4 5 6 4 5 6 7 8 9]
[[1 2 3 4]
 [5 6 4 5]
 [6 7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


# Matrices

In [65]:
from numpy import *
arr1 = array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
m = matrix(arr1)
print(m)
n = matrix('1 2 3 4; 4 5 6 7')
print(n)
print(diagonal(n))
print(n.min())
print(n.max())


[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[[1 2 3 4]
 [4 5 6 7]]
[1 5]
1
7


In [68]:
m = matrix('1 2 3; 4 5 6; 7 8 9')
n = matrix('1 2 3; 4 5 6;7 8 9')
o = m * n;
p = m + n;
print(o)
print(p)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Functions

In [70]:
def greet():  #Function definition
    print("Hello")
    print("Good Morning")
    
greet() #Function Call

Hello
Good Morning


In [74]:
def add(x,y): #arguments
    c = x + y
    print(c)
    return c #returns value to function
result = add(5,4)
print(result)

9
9


In [78]:
def add_sub(x,y): #arguments
    c = x + y
    d = x - y
    print(c)
    print(d)
    return c,d #returns value to function
result1,result2 = add_sub(5,4)
result = add_sub(5,4)
print(result1)
print(result2)
print(result)

9
1
9
1
9
1
(9, 1)


In [85]:
#Pass by Value: We pass only values
#Pass by Reference: We pass addresses also
#Python doesn't use any of the above concept

def update(x):
    print(id(x))
    x = 8
    print(id(x))
    print(x)
    
update(10)

a = 10
update(a)
print(a)

b = 10
print(id(b))
update(b)
print(b)


93966632131392
93966632131328
8
93966632131392
93966632131328
8
10
93966632131392
93966632131392
93966632131328
8
10


In [87]:
def update(x):
    print(id(x))
    x[1] = 8
    print(id(x))
    print(x)
    


lst = [10,20,30]
print(id(lst))
update(lst)
print(lst)

140137736899016
140137736899016
140137736899016
[10, 8, 30]
[10, 8, 30]


In [89]:
def add(a,b):#Formal Arguments: Arguments which are used when a function is defined.
    c = a + b
    print(c)
    
add(4,5)#Actual Arguments: Arguments which are actually passed when a function is called.

9


In [91]:
# Position
def person(name,age):
    print(name)
    print(age)
    
person('navin',28)
person(20,'navin')

navin
28
20
navin


In [92]:
# Keyword
def person(name,age):
    print(name)
    print(age)
    
person(age=28,name='navin')


navin
28


In [94]:
# Default
def person(name,age = 18):
    print(name)
    print(age)
    
person('navin')
person('navin',28)

navin
18
navin
28


In [96]:
#Variable Length
def sum(a,*b):
    print(a)
    print(b)
    c = a
    for i in b:
        c = c + i
    print(c)
    
sum(5,6,34,78)

5
(6, 34, 78)
123


In [101]:
#Keyworded Variable Length
def person(name,**data):
    print(name)
    print(data)
    for i,j in data.items():
        print(i,j)
    
    
person('sai',age=28,city='Mumbai',mobile = 99999)

sai
{'age': 28, 'city': 'Mumbai', 'mobile': 99999}
age 28
city Mumbai
mobile 99999


In [113]:
#Global Keyword

a = 10
print(id(a))
b = 20
c = 30
def some():
    a = 15
    global c # act like a global variable and changes can be seen globally
    c = 35
            #it is not possible to have both local and global c in the same function
    print(a,'function') #inside function the preference will always be given to the local variable
    print(b,'function') #global variable can be accessed from anywhere in the program 
    print(c,'function')
    
    x = globals()['a']
    print(id(x)) #both the ids of x and a are pointed to same address
    print(x)
    
    globals()['a'] = 15 #value of a globally changed to 15
some()
print(a) #outside the function the preference will always be given to the global variable
print(b)
print(c)

93966632131392
15 function
20 function
35 function
93966632131392
10
15
20
35


In [120]:
def count(lst):
    even = 0
    odd = 0
    
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd
lst = [1,2,3,4,5,6,7,8,9]
even,odd = count(lst)
print("Even : {} and Odd : {}".format(even,odd))

Even : 4 and Odd : 5


In [123]:
#Fibonocci Series

def fib(n):
    
    a = 0
    b = 1
    
    if n == 1:
        print(a)
    elif n<0:
        print('0')
    else:
        print(a)
        print(b)
        
        for i in range(2,n):
            c = a + b
            a = b
            b = c
            print(c)
fib(10)

0
1
1
2
3
5
8
13
21
34


In [124]:
#Factorial

def fact(n):
    f = 1
    for i in range(1,n+1):
        f = f * i
    return f
x = 4

print(result)

(9, 1)


# Recursion

In [126]:
#Calling function in itself

def greet():
    print("Hello")
    greet()
greet() #maxium recursion exceeded which is 1000

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hell

RecursionError: maximum recursion depth exceeded in comparison

In [131]:
import sys

sys.setrecursionlimit(2000) #limit can be adjusted
print(sys.getrecursionlimit())

i = 0
def greet():
    global i
    i+=1
    print("Hello",i)
    greet()
greet()

2000
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110
Hel

RecursionError: maximum recursion depth exceeded in comparison

In [132]:
#Factorial using Recursion

def fact(n):
    if n == 0:
        return 1
    return n*fact(n-1)

result = fact(5)
print(result)

120


# Anonymous Function

In [134]:
def square(a):  # Normal function and Functions are objects in python can be passed
    return a*a

result = square(5)
print(result)



25


In [135]:
f = lambda a : a*a
result = f(5)
print(result)

25


In [136]:
#Filter Map Reduce in python
def is_even(n):
    return n%2==0
nums = [1,2,3,4,5,6,7,8,9]
evens = list(filter(is_even,nums))
print(evens)

[2, 4, 6, 8]


In [139]:
def update(n):
    return n*2
nums = [1,2,3,4,5,6,7,8,9]
evens = list(filter(lambda n : n%2==0,nums))
doubles = list(map(update,evens))
print(evens)
print(doubles)

[2, 4, 6, 8]
[4, 8, 12, 16]


In [144]:
from functools import reduce
def add_all(a,b):
    return a+b
nums = [1,2,3,4,5,6,7,8,9]
evens = list(filter(lambda n : n%2==0,nums))
doubles = list(map(lambda n : n*2,evens))
sum = reduce(add_all,doubles)
print(evens)
print(doubles)
print(sum)

[2, 4, 6, 8]
[4, 8, 12, 16]
40


In [145]:
from functools import reduce

nums = [1,2,3,4,5,6,7,8,9]
evens = list(filter(lambda n : n%2==0,nums))
doubles = list(map(lambda n : n*2,evens))
sum = reduce(lambda a,b:a+b,doubles)
print(evens)
print(doubles)
print(sum)

[2, 4, 6, 8]
[4, 8, 12, 16]
40


# Decorators

In [152]:
def div(a,b):
    print(a/b)
div(4,2)
div(2,4)

def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inner

div1 = smart_div(div) #Decorators change the logic of function
div1(2,4)


2.0
0.5
2.0
